# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "122002d98ca255ec706ef8e5497b3723d6c6e163511761d116dac3aee87747d46cf1";
    path = fetchzip {
      url = "https://github.com/raysan5/raygui/archive/4b3d94f5df6a5a2aa86286350f7e20c0ca35f516.tar.gz";
      hash = "sha256-+UVvUOp+6PpnoWy81ZCqD8BR6sxZJhtQNYQfbv6SOy0=";
    };
  }
  {
    name = "12206311fbaae8a0adc35e4835ddd9bcc1ff8fff756c9df40e19133f007fa05d3948";
    path = fetchzip {
      url = "https://github.com/Hejsil/mecha/archive/refs/tags/0.9.0.tar.gz";
      hash = "sha256-F2FL0B/Mmlpf5hXZxt0WdZTeueQXT2+dCSwPTfUNtiU=";
    };
  }
  {
    name = "1220aa75240ee6459499456ef520ab7e8bddffaed8a5055441da457b198fc4e92b26";
    path = fetchzip {
      url = "https://github.com/raysan5/raylib/archive/5767c4cd059e07355ae5588966d0aee97038a86b.tar.gz";
      hash = "sha256-2wKecOJqtM207JIK7ZxhtpXkNa7LnFN86eHRWyfRjlg=";
    };
  }
  {
    name = "1220d32c92222ded6912529bbd502b2e0c5c5c2056c4b709ad0f6924d6524343a2d2";
    path = fetchzip {
      url = "https://github.com/Not-Nik/raylib-zig/archive/2d8e856009bf0ee60ef78bde78e32512bdaae714.tar.gz";
      hash = "sha256-F6mK5H82txS67y7PMX2BtQcQNuLdykVioWGUZcBlIqo=";
    };
  }
]
